# Bacterial 16S metabarcoding pipeline
#
# @sgelias
#
# Description: Generate quality reporter and perform taxonomic annotation for
# bacterial 16S metabarcoding sequencing product. See README.md file for details.


# Import the configuration file.
configfile: "config.yaml"


SUFFIX = ["fastqc.zip", "fastqc.html"]
FILES = config["samples"]


# Turn ouput files available for all rules ...
rule all:
    input:
        expand(
            "{directory}/{file}_{suffix}",
            directory=config["fastq_raw_quality"],
            file=FILES,
            suffix=SUFFIX,
        ),
        expand(
            "{directory}/{file}_FILTERED_{suffix}",
            directory=config["fastq_trimmed_quality"],
            file=FILES,
            suffix=SUFFIX,
        ),
        "{directory}/{file}".format(
            directory=config["otu_table"], 
            file="otu_table.tsv"
        ),


"""
Step: Trim ends of fastq files.
Software: Trimmomatic
Version: 0.39
Description: This step remove low quality ...

Important parameters:
"""


rule generate_quality_scores_raw:
    message:
        """--- Quality check of raw data with Fastqc."""
    input:
        expand(
            "{directory}/{file}.fastq", 
            directory=config["fastq_raw"], 
            file=FILES,
        ),
    output:
        expand(
            "{directory}/{file}_{suffix}",
            directory=config["fastq_raw_quality"],
            file=FILES,
            suffix=SUFFIX,
        ),
    log:
        config["fastq_raw_quality_log"],
    params:
        output_dir=config["fastq_raw_quality"],
    threads: 2
    shell:
        """
        mkdir -p {params.output_dir}
        fastqc -q \
            --outdir {params.output_dir} \
            --threads {threads} \
            {input} \
            &>> {log}
        """


"""
Step: Trim ends of fastq files.
Software: Trimmomatic
Version: 0.39
Description: This step remove low quality ...

Important parameters:
"""


rule trim_se:
    message:
        """--- Trimming raw data with Trimmomatic."""
    input:
        expand(
            "{directory}/{file}.fastq", 
            directory=config["fastq_raw"], 
            file=FILES,
        ),
    output:
        expand(
            "{directory}/{file}_FILTERED.fastq",
            directory=config["fastq_trimmed"],
            file=FILES,
        ),
    log:
        config["fastq_trimmed_log"],
    params:
        headcrop=20,
        slidingwindow="5:20",
        minlen=180,
        adapters="{adapters}:2:30:10".format(adapters=config["adapters"]),
        trimmomatic=config["trimmomatic"],
        workdir=config["fastq_trimmed"],
    threads: 2
    run:
        for file in input:

            filename = file.split("/")[-1].split(".")[0]

            target_output = [
                item for item in output if item \
                    .split("/")[-1] \
                    .startswith(filename)
            ]

            shell(
                """
                mkdir -p {params.workdir}
                java -jar {params.trimmomatic} \
                    SE -phred33 \
                    -threads {threads} \
                    {file} \
                    {target_output} \
                    ILLUMINACLIP:"{params.adapters}" \
                    HEADCROP:{params.headcrop} \
                    SLIDINGWINDOW:{params.slidingwindow} \
                    MINLEN:{params.minlen} \
                    &>> {log}
                """
            )


"""
Step: Trim ends of fastq files.
Software: Trimmomatic
Version: 0.39
Description: This step remove low quality ...

Important parameters:
"""


rule generate_quality_scores_trimmed:
    message:
        """--- Quality check of trimmed data with Fastqc."""
    input:
        trimmed_files=rules.trim_se.output,
    output:
        expand(
            "{directory}/{file}_FILTERED_{suffix}",
            directory=config["fastq_trimmed_quality"],
            file=FILES,
            suffix=SUFFIX,
        ),
    log:
        config["fastq_trimmed_quality_log"],
    params:
        output_dir=config["fastq_trimmed_quality"],
    threads: 4
    shell:
        """
        mkdir -p {params.output_dir}
        fastqc -q \
            --outdir {params.output_dir} \
            --threads {threads} \
            {input} \
            &>> {log}
        """


"""
Step: Trim ends of fastq files.
Software: Trimmomatic
Version: 0.39
Description: This step remove low quality ...

Important parameters:
"""


rule build_reference_database:
    message:
        """--- Building reference database."""
    input:
        config["reference"],
    output:
        expand(
            "{output_dir}/{output_prefix}.{blast_database_formats}",
            output_dir=config["reference_blast"],
            output_prefix="bacterial_16S",
            blast_database_formats=["nhr", "nin", "nsq"],
        ),
    params:
        dbtype="nucl",
        output_dir=config["reference_blast"],
        output_prefix="bacterial_16S",
    shell:
        """
        mkdir -p {params.output_dir}
        makeblastdb \
            -in {input} \
            -dbtype {params.dbtype} \
            -out {params.output_dir}/{params.output_prefix}
        """


"""
Step: Trim ends of fastq files.
Software: Trimmomatic
Version: 0.39
Description: This step remove low quality ...

Important parameters:
"""


rule convert_fastq_to_fasta:
    message:
        """--- Convert FASTQ to FASTA fromat."""
    input:
        expand(
            "{directory}/{file}_FILTERED.fastq",
            directory=config["fastq_trimmed"],
            file=FILES,
        ),
    output:
        expand(
            "{directory}/{file}_FILTERED.fasta",
            directory=config["fasta_trimmed"],
            file=FILES,
        ),
    run:
        for file in input:

            filename = file.split("/")[-1].split(".")[0]

            target_output = [
                item for item in output if item \
                    .split("/")[-1] \
                    .startswith(filename)
            ][0]

            shell(
                """
                sed -n '1~4s/^@/>/p;2~4p' \
                    {file} > {target_output}
                """
            )


"""
Step: Trim ends of fastq files.
Software: Trimmomatic
Version: 0.39
Description: This step remove low quality ...

Important parameters:
"""


rule perform_taxonomic_annotation:
    message:
        """--- Taxonomic annotation using blastn."""
    input:
        trimmed_files=rules.convert_fastq_to_fasta.output,
        reference_database=rules.build_reference_database.output,
    output:
        expand(
            "{directory}/{file}_FILTERED_BAC16S.csv",
            directory=config["tax_annotation"],
            file=FILES,
        ),
    params:
        evalue=1e-5,
        outfmt="10",
        max_target_seqs=50,
        perc_identity=0.95,
        max_hsps=50,
        db=rules.build_reference_database.params.output_prefix,
        db_dir=config["reference_blast"],
        output_dir=config["tax_annotation"],
    threads: 4
    run:
        for file in input.trimmed_files:

            filename = file.split("/")[-1].split(".")[0]

            target_output = [
                item for item in output if item \
                    .split("/")[-1] \
                    .startswith(filename)
            ][0]

            shell(
                """
                mkdir -p {params.output_dir}
                cd {params.output_dir}
                blastn \
                    -query {file} \
                    -evalue {params.evalue} \
                    -outfmt {params.outfmt} \
                    -num_threads {threads} \
                    -max_target_seqs {params.max_target_seqs} \
                    -perc_identity {params.perc_identity} \
                    -max_hsps {params.max_hsps} \
                    -db {params.db_dir}/{params.db} \
                    -out {target_output}
                """
            )


"""
Step: Trim ends of fastq files.
Software: Trimmomatic
Version: 0.39
Description: This step remove low quality ...

Important parameters:
"""


rule generate_count_table:
    message:
        """--- Generating taxon by sample count table."""
    input:
        rules.perform_taxonomic_annotation.output,
    output:
        "{directory}/{file}".format(
            directory=config["otu_table"], 
            file="otu_table.tsv"
        ),
    params:
        blast_dir=config["tax_annotation"],
        output_dir=config["otu_table"],
        reference_database=config["reference"],
        cut_suffix="",
        builder=config["otu_table_builder"],
    shell:
        """
        mkdir -p {params.output_dir}
        python {params.builder} \
            --blastdir {params.blast_dir} \
            --outputdir {params.output_dir}/otu_table.tsv \
            --reference_database {params.reference_database} \
            --cut_suffix '_L001_R1_001_FILTERED_BAC16S'
        """
