
# Install dependencies via CRAN
if (!"vegan" %in% installed.packages()) install.packages("vegan", dependencies = TRUE)
if (!"DT" %in% installed.packages()) install.packages("DT")
if (!"doParallel" %in% installed.packages()) install.packages("doParallel")
if (!"egg" %in% installed.packages()) install.packages("egg")
if (!"foreach" %in% installed.packages()) install.packages("foreach")
if (!"ggplot2" %in% installed.packages()) install.packages("ggplot2")
if (!"ggiraph" %in% installed.packages()) install.packages("ggiraph")
if (!"hrbrthemes" %in% installed.packages()) install.packages("hrbrthemes")
if (!"iNEXT" %in% installed.packages()) install.packages("iNEXT")
if (!"knitr" %in% installed.packages()) install.packages("knitr")
if (!"labdsv" %in% installed.packages()) install.packages("labdsv")
if (!"optparse" %in% installed.packages()) install.packages("optparse")
if (!"plotly" %in% installed.packages()) install.packages("plotly")
if (!"rlist" %in% installed.packages()) install.packages("rlist")
if (!"remotes" %in% installed.packages()) install.packages("remotes")
if (!"rmarkdown" %in% installed.packages()) install.packages("rmarkdown")
if (!"tidyverse" %in% installed.packages()) install.packages("tidyverse", dependencies = TRUE)
if (!"viridis" %in% installed.packages()) install.packages("viridis")


# Install dependencies via Biocondictor (uncomment if needed)
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
if (!requireNamespace("edgeR", quietly = TRUE)) BiocManager::install("edgeR")

# Load packages
library(DT)
library(doParallel)
library(egg)
library(edgeR)
library(foreach)
library(ggplot2)
library(ggiraph)
library(hrbrthemes)
library(iNEXT)
library(knitr)
library(labdsv)
library(optparse)
library(plotly)
library(rlist)
library(rmarkdown)
library(tidyverse)
library(vegan)
library(viridis)
